PATH_TO_MVTS: 'mvtsdatatoolkit/data/petdataset_01/'
PATH_TO_EXTRACTED_FEATURES: 'mvtsdatatoolkit/data/extracted_features/'
META_DATA_TAGS: ['id', 'lab', 'st', 'et']
MVTS_PARAMETERS:
  - 'TOTUSJH'
  - 'TOTBSQ'
  - 'TOTPOT'
  - 'TOTUSJZ'
  - 'ABSNJZH'
  - 'SAVNCPP'
  - 'USFLUX'
  - 'TOTFZ'
  - 'MEANPOT'
  - 'EPSZ'
  - 'MEANSHR'
  - 'SHRGT45'
  - 'MEANGAM'
  - 'MEANGBT'
  - 'MEANGBZ'
  - 'MEANGBH'
  - 'MEANJZH'
  - 'TOTFY'
  - 'MEANJZD'
  - 'MEANALP'
  - 'TOTFX'
  - 'EPSY'
  - 'EPSX'
  - 'R_VALUE'
STATISTICAL_FEATURES:
  - 'get_min'
  - 'get_max'
  - 'get_median'
  - 'get_mean'
  - 'get_stddev'
  - 'get_var'
  - 'get_skewness'
  - 'get_kurtosis'
  - 'get_no_local_maxima'
  - 'get_no_local_minima'
  - 'get_no_local_extrema'
  - 'get_no_zero_crossings'
  - 'get_mean_local_maxima_value'
  - 'get_mean_local_minima_value'
  - 'get_no_mean_local_maxima_upsurges'
  - 'get_no_mean_local_minima_downslides'
  - 'get_difference_of_mins'
  - 'get_difference_of_maxs'
  - 'get_difference_of_means'
  - 'get_difference_of_stds'
  - 'get_difference_of_vars'
  - 'get_difference_of_medians'
  - 'get_dderivative_mean'
  - 'get_gderivative_mean'
  - 'get_dderivative_stddev'
  - 'get_gderivative_stddev'
  - 'get_dderivative_skewness'
  - 'get_gderivative_skewness'
  - 'get_dderivative_kurtosis'
  - 'get_gderivative_kurtosis'
  - 'get_linear_weighted_average'
  - 'get_quadratic_weighted_average'
  - 'get_average_absolute_change'
  - 'get_average_absolute_derivative_change'
  - 'get_positive_fraction'
  - 'get_negative_fraction'
  - 'get_last_value'
  - 'get_sum_of_last_K'
  - 'get_mean_last_K'
  - 'get_slope_of_longest_mono_increase'
  - 'get_slope_of_longest_mono_decrease'
  - 'get_avg_mono_increase_slope'
  - 'get_avg_mono_decrease_slope'

